name: Test Backend
description: Runs tests for backend with optional coverage report
inputs:
  coverage:
    description: Run test coverage report
    required: false
    default: 'false'

runs:
  using: composite
  steps:

    - name: Run Standard Tests
      shell: bash
      continue-on-error: true
      run: |
          cd backend
          export NODE_ENV=test
          export NODE_OPTIONS='--experimental-vm-modules --no-warnings=ExperimentalWarning'
          mkdir -p test-results
          npx jest --testPathIgnorePatterns="src/__tests__/setup/|server.test.js" \
          --json --outputFile=test-results/standard-results.json \
          --testTimeout=30000 --silent 2>&1 | tee test-results/standard-output.log
          

    - name: Run Integration Tests
      shell: bash
      continue-on-error: true
      run: |
        cd backend
        export NODE_ENV=test
        export NODE_OPTIONS='--experimental-vm-modules --no-warnings=ExperimentalWarning'
        mkdir -p test-results
        npx jest server.test.js \
        --json --outputFile=test-results/integration-results.json \
        --testTimeout=60000 --silent --forceExit 2>&1 | tee test-results/integration-output.log

    - name: Run Tests with coverage
      if: ${{ inputs.coverage == 'true' }}
      shell: bash
      continue-on-error: true
      run: |
        cd backend
        export NODE_ENV=test
        export NODE_OPTIONS='--experimental-vm-modules --no-warnings=ExperimentalWarning'
        mkdir -p test-results
        npx jest --coverage --coverageDirectory=coverage \
        --json --outputFile=test-results/coverage-results.json \
        --testTimeout=30000 --silent 2>&1 | tee test-results/coverage-output.log

    - name: Upload All Results
      if: always()
      uses: actions/upload-artifact@v6
      with:
        name: backend-test-results-${{ github.sha }}
        path: |
          backend/test-results/
          backend/coverage/
        retention-days: 30

    - name: Test Summary
      shell: bash
      if: always()
      run: |
        echo "## Backend Test Results" >> $GITHUB_STEP_SUMMARY
        echo "- Commit: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
        echo "- Artifacts uploaded with 30 day retention" >> $GITHUB_STEP_SUMMARY